[toolchain]

[features]
resolution = true
skip-lint = false

[programs.devnet]
vault = "Cf8PP8nDWSspGghGXH3KtMwMMviMPGQX4jesPf4nBbuJ"

[provider]
cluster = "devnet"
wallet = "~/.config/solana/id.json"

[scripts]
initialize = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/initialize.ts"
test = "pnpm exec ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"

[hooks]
