[toolchain]
anchor_version = "1.0.2"
package_manager = "yarn"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_escrow = "7SwmEztx634fXki884aMpgpmvGSYcLiHgJFGki2TXrBr"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test --test anchor-litesvm-tests"

[hooks]
