[toolchain]
anchor_version = "1.0.0-rc.2"

[features]
resolution = true
skip-lint = false

[programs.localnet]
stablecoin = "GgvDxkMn9WbZJ5sJEemUdcRrrw1y6LdNTaR7QEacvV9R"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test -p stablecoin"

[hooks]
